Publish button
oss-slu/DigitalBonesBox pull request #42
Opened 2024-09-30 20:40 UTC by JoshBudzynski

Issue #18 

Creates a Button that has an action connected to it. As the instructions detail. 

Needs to add the updating of a GitHub, looking for some guidance on how to do this and what I am updating.

2024-09-30 22:17 UTC, tluke900 reviewed
Only significant missing piece is the git push.

2024-09-30 22:17 UTC, tluke900 commented on .github/Button.html
> +        button.addEventListener('click', async () => {
No implementation for Git Pushes, listener is present for such actions however in the future.

2024-09-30 22:17 UTC, tluke900 commented on .github/Button.html
> +    /* Style the button */
Correctly matches specifications of the button

2024-09-30 22:17 UTC, tluke900 commented on .github/Button.html
> +        // I dont know the idea behind this quite yet looking for tips
Once you begin implementing the Git Push, create a arbitrary directory to push too for now.

2024-10-01 17:42 UTC, kate-holdener commented on .github/Button.html
Please move this button out of the .github directory

2024-10-04 04:54 UTC, jacksayshi requested changes
Thank you for working on this issue.
Here are few things to get this merged Please move HTML out of .github and for publishing to github "data" branch we can use a nodejs server with library like simplegit.

2024-10-08 13:54 UTC, kate-holdener commented on Data_Directory/.DS_Store
Please remove this file and the Data_Directory

2024-10-08 13:54 UTC, kate-holdener commented on .DS_Store
Please remove this file

2024-10-08 13:57 UTC, kate-holdener commented on BoneServer.js
> +    await git.push('origin', 'Publish_Button');
Your push should be going here: https://github.com/oss-slu/DigitalBonesBox/tree/data/databones

2024-10-08 19:47 UTC, jacksayshi requested changes
Thank you for working on the changes.
As required it is publishing changes to git. But, we need that changes to be pushed not to the branch you have created and worked on. It should be Origin "data" branch. 
If you could make that change you also wouldnt need Data_Directory. 
Please make these changes to get this merged

2024-10-11 01:06 UTC, closed without merging