Basic Text display for bone set
oss-slu/DigitalBonesBox pull request #45
Opened 2024-10-06 17:35 UTC by tluke900

Fixes #15 

Basic HTML layout created, displaying example layout of upper-limb bone set. 

HTML for bone displays.

Links not created yet, initial commit for Proof of concept.

2024-10-06 17:41 UTC, kate-holdener commented
@tluke900 That's a nice start with placeholder for text. The idea is to not hard-code any information, but pull it dynamically from the data branch of the repo, where the information is defined in the JSON files.

2024-10-06 19:05 UTC, jacksayshi requested changes
Its is a nice structure. Clean and simple. Easy to read and understand. Now lets build on this. We need our application to pull data from the data branch (where our data exists). They will be stored as json files. 
They should be fetched and displayed in the format you created.

2024-10-08 13:59 UTC, kate-holdener commented on templates/index.html
> +            fetch('/Data_Directory/boneSet.json')
You should be fetching from here: https://github.com/oss-slu/DigitalBonesBox/blob/data/databones/json/boneset.json

2024-10-08 19:33 UTC, jacksayshi commented
I tried to run your code. But the HTML page was displaying as a blank page. Please try running it again on your side.

2024-10-10 02:26 UTC, tluke900 reviewed
Should be fixed to address issues.

2024-10-10 18:39 UTC, jacksayshi approved these changes

2024-10-10 18:40 UTC, merged