Issue 47
oss-slu/DigitalBonesBox pull request #50
Opened 2024-10-14 01:21 UTC by JoshBudzynski

Solves Issue 47

Adds a next and previous button before the arbitrary bone sets we have so far, and displays the information.

Might break when there is a larger data set.

2024-10-14 22:37 UTC, tluke900 reviewed
Overall very similar to mine, completed very similarly.

2024-10-14 22:37 UTC, tluke900 commented on Data_Directory/Bone_Directory/boneset.html
> +            const set = bonesetData[index];
We did this a little differently, working on standardization later would be helpful.

2024-10-15 20:58 UTC, kate-holdener commented
It seems like this code does not match the directory structure in main.

2024-10-15 21:11 UTC, kate-holdener commented on .DS_Store
Do not add these files to the repo

2024-10-15 21:13 UTC, kate-holdener commented on Button.html
This file is irrelevant to the issue you are working on.

2024-10-16 03:03 UTC, jacksayshi requested changes
Thanks for working on this. 
But I think you might have created a new branch based on your old branch. Please restructure your branch based on latest commits in main (As we have agreed on a format 
for now). And make changes to html in that file structure.

2024-10-22 19:43 UTC, closed without merging