Fixe #46
oss-slu/DigitalBonesBox pull request #51
Opened 2024-10-14 18:24 UTC by tluke900

#46 

Added hardcoded loading of boneset names and drop down to select for them. Now only loads the selected boneset.

Drop down menu for bonesets and updated load button. 

Dynamic Loading work in progress, for future sets if added.

2024-10-14 22:26 UTC, Balijah commented on templates/boneset.html
> +    // Clear existing options
Not sure what this is, is it necessary?

2024-10-14 22:34 UTC, Balijah commented on templates/boneset.html
> +
Good comments

2024-10-15 21:02 UTC, kate-holdener commented
When I click "Load options" many times, I get a lot of duplicated information loaded.
<img width="1675" alt="Screenshot 2024-10-15 at 4 01 16 PM" src="https://github.com/user-attachments/assets/ebde40fc-2fdf-4a66-8b77-96b9011728ff">

2024-10-16 00:30 UTC, jacksayshi requested changes
Thanks for working on this.
The populateDropdown function that is adding options to the dropdown is getting called everytime load button is being clicked and this is addinf duplicate list of entries to the dropdown. 
We do not have to preserve the original buttons. Also we can try to fetch and populate dropdown while the page is loading (so that we dont call the function again). Here is what this issue solution could look like 
![image](https://github.com/user-attachments/assets/f820c4aa-97d9-4a6e-bbca-5f7004a9d85d)

2024-10-22 03:40 UTC, jacksayshi approved these changes
We can merge these changes for now. We can make some more improvements like error handling and effective functions calls later.

2024-10-22 03:40 UTC, merged