Addresses Issue #49.
oss-slu/DigitalBonesBox pull request #53
Opened 2024-10-14 22:29 UTC by Balijah

The image is being pulled from the remote repo and displayed properly but still working on getting the annotations to be pulled and displayed properly.

2024-10-15 21:06 UTC, kate-holdener commented
> The image is being pulled from the remote repo and displayed properly but still working on getting the annotations to be pulled and displayed properly.

Please provide the required information in the PR. Your PR descriptions are very minimal and challenging to interpret.

2024-10-15 21:07 UTC, kate-holdener commented on Data_Directory/Images_Directory/.DS_Store
Do not include these files in your commits.

2024-10-15 21:07 UTC, kate-holdener commented
Your directory structure does not match the main branch.

2024-10-15 21:09 UTC, kate-holdener commented on Editor_Directory/index.html
> +        document.getElementById('bone-image').src = imagePath;
Your image file is hard coded, it should be dynamic, based on the bone id

2024-10-16 04:09 UTC, jacksayshi requested changes
Thanks for working on this.
I think your branch is based on your previous sprint branch. Please pull latest commits from origin main of repo (it has the structure we all agreed on for now) and make changes to HTML based on issue requirement. 
Here is the image of current HTML page of our bones. We need corresponding images from data branch to be displayed along with other details.
<img width="818" alt="image" src="https://github.com/user-attachments/assets/880f5671-23fc-424f-a76f-4703f0c58e79">

2024-10-22 03:36 UTC, merged